dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/dataset_contributors/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.dataset_contributors setup.py nosetests --ckan --with-pylons=ckanext/dataset_contributors/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.dataset_contributors --rednose

after_success: coveralls
