dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/orcid_datasets/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.orcid_datasets setup.py nosetests --ckan --with-pylons=ckanext/orcid_datasets/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.orcid_datasets --rednose

after_success: coveralls
